services:
  - type: web
    name: aesa-squadron-inventory
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: aesa-squadron-inventory
          property: port